//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class coffees
    {
        public int Id { get; set; }
        public string CofeeName { get; set; }
        public Nullable<int> CofeePrice { get; set; }
        public string CofeeImagePath { get; set; }
        public string CofeeDescription { get; set; }
        public Nullable<bool> CoffeeType { get; set; }
    }
}
